### ISSUE TITLE
Install Node to flex CLI skills

### ISSUE THREAD

**Issue by jshawl** [ga-wdi-lessons/cli-intro#1]
Node, 5.5.0?
When are we installing node?  In earlier cohorts, we decided to put it in a lesson.  It would be a good time to flex CLI skills.  Which lesson?
How does this affect lessons/exercises?

**Comment by jsm13** [comment]
Closing; node included in installfest as of https://github.com/ga-dc/installfest/commit/bece497412d342521c2b2fff369d84f0f8cc56e5
